export interface SeedBook {
  title: string;
  author: string;
  publisher: string;
  genre: string;
  price: number;
  stock: number;
}

export const SEED_BOOKS: SeedBook[] = [
  {
    title: 'La casa de los espíritus',
    author: 'Isabel Allende',
    publisher: 'Sudamericana',
    genre: 'Realismo mágico',
    price: 18990,
    stock: 12,
  },
  {
    title: 'De amor y de sombra',
    author: 'Isabel Allende',
    publisher: 'Sudamericana',
    genre: 'Novela',
    price: 15990,
    stock: 7,
  },
  {
    title: 'Eva Luna',
    author: 'Isabel Allende',
    publisher: 'Sudamericana',
    genre: 'Novela',
    price: 15990,
    stock: 4,
  },
  {
    title: 'Paula',
    author: 'Isabel Allende',
    publisher: 'Sudamericana',
    genre: 'Ensayo',
    price: 14990,
    stock: 0,
  },
  {
    title: 'Hija de la fortuna',
    author: 'Isabel Allende',
    publisher: 'Sudamericana',
    genre: 'Novela histórica',
    price: 16990,
    stock: 9,
  },
  {
    title: 'Largo pétalo de mar',
    author: 'Isabel Allende',
    publisher: 'Sudamericana',
    genre: 'Novela histórica',
    price: 19990,
    stock: 15,
  },
  {
    title: 'Veinte poemas de amor y una canción desesperada',
    author: 'Pablo Neruda',
    publisher: 'Seix Barral',
    genre: 'Poesía',
    price: 9990,
    stock: 25,
  },
  {
    title: 'Canto general',
    author: 'Pablo Neruda',
    publisher: 'Seix Barral',
    genre: 'Poesía',
    price: 17990,
    stock: 6,
  },
  {
    title: 'Confieso que he vivido',
    author: 'Pablo Neruda',
    publisher: 'Seix Barral',
    genre: 'Ensayo',
    price: 16990,
    stock: 3,
  },
  {
    title: 'Odas elementales',
    author: 'Pablo Neruda',
    publisher: 'Seix Barral',
    genre: 'Poesía',
    price: 11990,
    stock: 0,
  },
  {
    title: 'Desolación',
    author: 'Gabriela Mistral',
    publisher: 'Editorial Universitaria',
    genre: 'Poesía',
    price: 10990,
    stock: 8,
  },
  {
    title: 'Tala',
    author: 'Gabriela Mistral',
    publisher: 'Editorial Universitaria',
    genre: 'Poesía',
    price: 10990,
    stock: 0,
  },
  {
    title: 'Lagar',
    author: 'Gabriela Mistral',
    publisher: 'Editorial Universitaria',
    genre: 'Poesía',
    price: 11990,
    stock: 5,
  },
  {
    title: 'Los detectives salvajes',
    author: 'Roberto Bolaño',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 24990,
    stock: 10,
  },
  {
    title: '2666',
    author: 'Roberto Bolaño',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 32990,
    stock: 0,
  },
  {
    title: 'Estrella distante',
    author: 'Roberto Bolaño',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 14990,
    stock: 6,
  },
  {
    title: 'Nocturno de Chile',
    author: 'Roberto Bolaño',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 13990,
    stock: 11,
  },
  {
    title: 'Llamadas telefónicas',
    author: 'Roberto Bolaño',
    publisher: 'Anagrama',
    genre: 'Cuento',
    price: 13990,
    stock: 2,
  },
  {
    title: 'El obsceno pájaro de la noche',
    author: 'José Donoso',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 21990,
    stock: 4,
  },
  {
    title: 'Coronación',
    author: 'José Donoso',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 15990,
    stock: 0,
  },
  {
    title: 'El lugar sin límites',
    author: 'José Donoso',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 12990,
    stock: 7,
  },
  {
    title: 'Bonsái',
    author: 'Alejandro Zambra',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 11990,
    stock: 14,
  },
  {
    title: 'Formas de volver a casa',
    author: 'Alejandro Zambra',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 14990,
    stock: 9,
  },
  {
    title: 'Poeta chileno',
    author: 'Alejandro Zambra',
    publisher: 'Anagrama',
    genre: 'Novela',
    price: 19990,
    stock: 0,
  },
  {
    title: 'Nosotras que nos queremos tanto',
    author: 'Marcela Serrano',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 14990,
    stock: 5,
  },
  {
    title: 'Antigua vida mía',
    author: 'Marcela Serrano',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 14990,
    stock: 3,
  },
  {
    title: 'Un viejo que leía novelas de amor',
    author: 'Luis Sepúlveda',
    publisher: 'Tusquets',
    genre: 'Novela',
    price: 12990,
    stock: 18,
  },
  {
    title: 'Historia de una gaviota y del gato que le enseñó a volar',
    author: 'Luis Sepúlveda',
    publisher: 'Tusquets',
    genre: 'Novela',
    price: 9990,
    stock: 30,
  },
  {
    title: 'Patagonia Express',
    author: 'Luis Sepúlveda',
    publisher: 'Tusquets',
    genre: 'Ensayo',
    price: 12990,
    stock: 2,
  },
  {
    title: 'La reina Isabel cantaba rancheras',
    author: 'Hernán Rivera Letelier',
    publisher: 'Planeta',
    genre: 'Novela',
    price: 13990,
    stock: 8,
  },
  {
    title: 'El arte de la resurrección',
    author: 'Hernán Rivera Letelier',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 14990,
    stock: 6,
  },
  {
    title: 'Santa María de las flores negras',
    author: 'Hernán Rivera Letelier',
    publisher: 'Seix Barral',
    genre: 'Novela histórica',
    price: 14990,
    stock: 4,
  },
  {
    title: 'La última niebla',
    author: 'María Luisa Bombal',
    publisher: 'Zig-Zag',
    genre: 'Novela',
    price: 8990,
    stock: 10,
  },
  {
    title: 'La amortajada',
    author: 'María Luisa Bombal',
    publisher: 'Zig-Zag',
    genre: 'Novela',
    price: 8990,
    stock: 0,
  },
  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    publisher: 'Sudamericana',
    genre: 'Realismo mágico',
    price: 22990,
    stock: 20,
  },
  {
    title: 'El amor en los tiempos del cólera',
    author: 'Gabriel García Márquez',
    publisher: 'Sudamericana',
    genre: 'Novela',
    price: 19990,
    stock: 8,
  },
  {
    title: 'Crónica de una muerte anunciada',
    author: 'Gabriel García Márquez',
    publisher: 'Sudamericana',
    genre: 'Novela',
    price: 12990,
    stock: 13,
  },
  {
    title: 'El coronel no tiene quien le escriba',
    author: 'Gabriel García Márquez',
    publisher: 'Sudamericana',
    genre: 'Novela',
    price: 10990,
    stock: 6,
  },
  {
    title: 'Relato de un náufrago',
    author: 'Gabriel García Márquez',
    publisher: 'Tusquets',
    genre: 'Ensayo',
    price: 11990,
    stock: 4,
  },
  {
    title: 'La ciudad y los perros',
    author: 'Mario Vargas Llosa',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 18990,
    stock: 7,
  },
  {
    title: 'Conversación en La Catedral',
    author: 'Mario Vargas Llosa',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 24990,
    stock: 3,
  },
  {
    title: 'La fiesta del Chivo',
    author: 'Mario Vargas Llosa',
    publisher: 'Alfaguara',
    genre: 'Novela histórica',
    price: 21990,
    stock: 5,
  },
  {
    title: 'La tía Julia y el escribidor',
    author: 'Mario Vargas Llosa',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 16990,
    stock: 0,
  },
  {
    title: 'Ficciones',
    author: 'Jorge Luis Borges',
    publisher: 'Lumen',
    genre: 'Cuento',
    price: 15990,
    stock: 12,
  },
  {
    title: 'El Aleph',
    author: 'Jorge Luis Borges',
    publisher: 'Lumen',
    genre: 'Cuento',
    price: 15990,
    stock: 9,
  },
  {
    title: 'El libro de arena',
    author: 'Jorge Luis Borges',
    publisher: 'Lumen',
    genre: 'Cuento',
    price: 13990,
    stock: 4,
  },
  {
    title: 'Rayuela',
    author: 'Julio Cortázar',
    publisher: 'Alfaguara',
    genre: 'Novela',
    price: 23990,
    stock: 0,
  },
  {
    title: 'Bestiario',
    author: 'Julio Cortázar',
    publisher: 'Alfaguara',
    genre: 'Cuento',
    price: 12990,
    stock: 6,
  },
  {
    title: 'Final del juego',
    author: 'Julio Cortázar',
    publisher: 'Alfaguara',
    genre: 'Cuento',
    price: 12990,
    stock: 5,
  },
  {
    title: 'Pedro Páramo',
    author: 'Juan Rulfo',
    publisher: 'Cátedra',
    genre: 'Realismo mágico',
    price: 11990,
    stock: 16,
  },
  {
    title: 'El llano en llamas',
    author: 'Juan Rulfo',
    publisher: 'Cátedra',
    genre: 'Cuento',
    price: 11990,
    stock: 8,
  },
  {
    title: 'Como agua para chocolate',
    author: 'Laura Esquivel',
    publisher: 'Planeta',
    genre: 'Realismo mágico',
    price: 14990,
    stock: 10,
  },
  {
    title: 'El laberinto de la soledad',
    author: 'Octavio Paz',
    publisher: 'Cátedra',
    genre: 'Ensayo',
    price: 16990,
    stock: 3,
  },
  {
    title: 'Piedra de sol',
    author: 'Octavio Paz',
    publisher: 'Lumen',
    genre: 'Poesía',
    price: 9990,
    stock: 7,
  },
  {
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    publisher: 'Cátedra',
    genre: 'Clásicos',
    price: 29990,
    stock: 11,
  },
  {
    title: 'Novelas ejemplares',
    author: 'Miguel de Cervantes',
    publisher: 'Cátedra',
    genre: 'Clásicos',
    price: 17990,
    stock: 2,
  },
  {
    title: 'Space Invaders',
    author: 'Nona Fernández',
    publisher: 'Planeta',
    genre: 'Novela',
    price: 11990,
    stock: 9,
  },
  {
    title: 'La dimensión desconocida',
    author: 'Nona Fernández',
    publisher: 'Planeta',
    genre: 'Novela',
    price: 16990,
    stock: 6,
  },
  {
    title: 'Nuestra parte de noche',
    author: 'Mariana Enriquez',
    publisher: 'Anagrama',
    genre: 'Terror',
    price: 26990,
    stock: 8,
  },
  {
    title: 'Las cosas que perdimos en el fuego',
    author: 'Mariana Enriquez',
    publisher: 'Anagrama',
    genre: 'Terror',
    price: 15990,
    stock: 0,
  },
];
